### ISSUE TITLE
strfmt does not accept vars as format string

### ISSUE THREAD

**Issue by GoWind** [kumarshantanu/stringer#1]
strfmt accepts only a string literal as the format string. It would be nice to have the format string being a var that holds the format string.
 Some format strings are canned at compile time and stored in a var that can be audited. It makes it easier to reuse them instead of creating a string literal at the call site.

**Comment by kumarshantanu** [comment]
`strfmt` leverages the string literal to do the pre-computation optimization. Does the following alternative work for you?

``` clojure
(defn make-str
  [known arg]
  (stringer.core/strfmt "literal format %s taking %d arg" known arg))
```

Another alternative would be to add a function to stringer that returns a function like the one above.

**Comment by GoWind** [comment]
No it does not. This complects by peppering the code with a  bunch of make-msg-str fn calls
